# Generated by Django 5.2 on 2025-05-13 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, unique=True, verbose_name='Назва категорії')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug категорії')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Назва товару')),
                ('slug', models.SlugField(max_length=200, verbose_name='Slug товару')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Ціна')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Кількість на складі')),
                ('available', models.BooleanField(default=True, verbose_name='Доступність')),
                ('product_type', models.CharField(choices=[('ELECTRONICS', 'Електроніка'), ('APPAREL', 'Одяг'), ('FOOD', 'Продукти харчування'), ('BOOKS', 'Книги')], default='ELECTRONICS', max_length=50, verbose_name='Тип товару')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата оновлення')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.category', verbose_name='Категорія')),
            ],
        ),
    ]
