# Generated by Django 5.2 on 2025-05-20 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_category_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('MEMBRANIK', 'Мембранні'), ('MECHANIK', 'Механічні')], default='MECHANIK', max_length=50, verbose_name='Тип товару'),
        ),
    ]
