# Generated by Django 5.2 on 2025-05-20 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
